#!/bin/bash
#title           :build
#description     :This script will compile the code and create the files
#author		       :dodiaraculus17
#date            :20161101
#version         :0.1    
#usage		       :./build or sudo ./build
#notes           :
#bash_version    :4.1.5(1)-release
#==============================================================================

#Important Version Variables
VERSION="1.0.0"

#Show the title screen
echo " _             __ _                 "
echo "| |_ ___  ___ / _| | __ _ _ __ ___  "
echo "| __/ _ \/ __| |_| |/ __ | ___/ _ \ "
echo "| ||  __/ (__|  _| | (_| | | |  __/ "
echo "\__\___|\___|_| |_|\__,_|_|  \___|  "
echo "You are installing tecflare webister version $VERSION"

#Make sure only root is allowed.
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root! Please contact Tecflare, if you are experiencing errors." 1>&2
   exit 1
fi


sudo apt-get update

command -v python >/dev/null 2>&1 || { echo >&2 "I require python but it's not installed.  Installing..."; sudo apt-get install -y python dialog; }
command -v php >/dev/null 2>&1 || { echo >&2 "I require php but it's not installed.  Installing..."; sudo apt-get install -y php5;}
command -v telnet >/dev/null 2>&1 || { echo >&2 "I require telnet but it's not installed.  Installing..."; sudo apt-get install -y telnet; }
command -v mysql >/dev/null 2>&1 || { echo >&2 "I require mysql but it's not installed.  Installing..."; sudo apt-get install -y mysql; }
if python build.py; then
    echo "Exit code of 0, success!!"
else
    echo "Exit code of $?, failure!!"
    exit 1
fi

echo "Enter the password again please:"

read PASS;
mysql -u root -p -e "CREATE DATABASE webister;"
php install.php $PASS
id -u webister &>/dev/null || useradd webister 
mkdir -p /var/webister
sudo chmod +x interface/execute

cp -r interface /var/webister/interface
cp files/service /etc/init.d/webister
chmod +x /etc/init.d/webister
cp python/server.py /var/webister
cp files/command /usr/bin/webister
sudo chmod +x /usr/bin/webister
service mysql start
sudo adduser webister sudo
mkdir /var/webister/8080
cp files/index.php /var/webister/8080/
chmod -R 777 /var/webister/8080/

echo "Starting the Service"
if service webister start; then
    echo "Service: Exit code of 0, success!!"
else
    echo "Service: Exit code of $?, failure!!"
    exit 1
fi

echo "The installation is now complete."
